accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import ( 
    LogoutView,
    PasswordResetView, 
    PasswordChangeView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from . views import (
    SignUpView, ProfileView, ActivateAccount, CustomLoginView,
    ApiSignUpView, ApiLogInView
)
from rest_framework.authtoken.views import obtain_auth_token


app_name = 'accounts'

urlpatterns = [
    path('api-signup/', ApiSignUpView.as_view(), name='api_sign_up'),
    path('api-login/', ApiLogInView.as_view(), name='api_log_in'),
    path('login/', CustomLoginView.as_view(
        redirect_authenticated_user=True, template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/<uuid:pk>/', ProfileView.as_view(), name='profile'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),

    path('change-password/',
        PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url = reverse_lazy('quiz:start_page')
        ),
        name='change_password'),

    path('password-reset/',
        PasswordResetView.as_view(
            template_name='registration/password-reset/password_reset.html',
            subject_template_name='registration/password-reset/password_reset_subject.txt',
            email_template_name='registration/password-reset/password_reset_email.html',
            success_url = reverse_lazy('accounts:login')
        ),
        name='password_reset'),

    path('password-reset/done/',
        PasswordResetDoneView.as_view(
            template_name='registration/password-reset/password_reset_done.html'
        ),
        name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='registration/password-reset/password_reset_confirm.html',
            success_url = reverse_lazy('accounts:login')
        ),
        name='password_reset_confirm'),

    path('password-reset-complete/',
        PasswordResetCompleteView.as_view(
            template_name='registration/password-reset/password_reset_complete.html'
        ),
        name='password_reset_complete'),
]

api/urls.py
from django.urls import path, include
from .views import (CategoryListView, QuestionListView, QuestionDetailsView,
                    ProgressByCategoryListView,
                    AttemptQuizView, ResultView, DashboardView,
                    TimeOverView, LeaderBoardView)

app_name = 'quiz_api'

urlpatterns = [

    path('category-list/', CategoryListView.as_view(), name='category_list'),
    
    path('question-list/<uuid:category_pk>/',
         QuestionListView.as_view(), name='question_list'),
    path('question-detail/<uuid:question_pk>/',
         QuestionDetailsView.as_view(), name='question_detail'),
    
    path('progress-list/<uuid:category_pk>/',
         ProgressByCategoryListView.as_view(), name='progress_list'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    
    path('attempt-quiz/<uuid:category_pk>/',
         AttemptQuizView.as_view(), name='attempt_quiz'),
    path('result/<uuid:category_pk>/',
         ResultView.as_view(), name='result'),
    path('time-over/<uuid:category_pk>/',
         TimeOverView.as_view(), name='time_over'),
    path('leaderboard/<uuid:category_pk>/',
         LeaderBoardView.as_view(), name='leaderboard'),

]

quiz/urls.py
from django.urls import path
from . views import ExamListView, ResultPageListView, StartPage, ExamCalculationView

app_name = 'quiz'

urlpatterns = [
    path('', StartPage.as_view(), name='start_page'),
    path('quiz/',
         ExamListView.as_view(), name='question_page'),
    path('results/', ResultPageListView.as_view(), name='result_page'),
    path('calculate/', ExamCalculationView.as_view(), name='calculation_page'),
]

quiz_me/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.views.generic.base import TemplateView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'), 
]

quiz_uuid/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('quiz.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),


]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{% block title %}Quiz Me{% endblock title %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 
  <!-- CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

</head>
<body>
<header> 
<!-- Fixed navbar -->
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4
    mb-3 bg-white border-bottom shadow-sm">
    <a href="{% url 'quiz:start_page' %}" class="navbar-brand my-0 mr-md-auto
    font-weight-normal">Quiz Me</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
            Hi {{user.email}}
            <a class="btn btn-outline-success" href="{% url 'accounts:change_password' %}">Change Password</a>
            <a class="btn btn-outline-secondary" href="{% url 'accounts:profile' pk=user.uuid %}">Profile</a>
            <a class="btn btn-outline-danger" href="{% url 'accounts:logout' %}">Log Out</a>
        {% else %}
            <p></p>
        {% endif %}
    </nav>
</div>
</header>
  <main class="container">
    <div class="text-center">
        {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}}">
            {{message}}
          </div>
    </div>
        {% endfor %}
        {% endif %}
        <div class="container">
          <div class="text-left">
          {% block content %}
          {% endblock content %}
          </div> 
        </div>
  </main>


  <!-- JavaScript -->
  <!-- JS, Popper.js, and jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
</body>
</html> 

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load mathfilters %}
{% load crispy_forms_tags%}

{% block content %}

<div style="padding-left: 10px; padding-right: 10px;"></div>
<div id="start-time" style="display: none;">{{start_time|date:'Y-m-d H:i:s'}}</div>
<div id="end-time" style="display: none;">{{end_time|date:'Y-m-d H:i:s'}}</div>
<h5>Time left: <p id="countdown" style="position: relative; padding: 0%;"></p></h5>
<br>
<div class="progress" style="padding: 0%;">
    <div class="progress-bar bg-success" role="progressbar" id="pg" aria-valuenow="60"
        aria-valuemin="0" aria-valuemax="100" style="width:
        {% with progress_bar=page_obj.number|mul:100 total_pages=page_obj.paginator.num_pages %}
        {{ progress_bar|div:total_pages}}%" %>
        {% endwith %}
    </div>
</div>

{% for question in questions %}    <hr>
    <form method="POST" id="myform" action="{% url 'quiz:calculation_page' %}">
        {% csrf_token %}
            <b>{{page_obj.number}}] {{question.title}}</b>  
                <input type="hidden" id="question_id" name="question_id" value="{{question.id}}">
                    {% if question.question_type == "MCQ" %}
                        {% for mcq in mcqs %}
                            {% if mcq.question.id == question.id %} <br>
                                <input type="radio" id=Option value="1" class="rb" name="user_answer"> {{mcq.option1}}<br>
                                <input type="radio" id=Option value="2" class="rb" name="user_answer"> {{mcq.option2}}<br>
                                <input type="radio" id=Option value="3" class="rb" name="user_answer"> {{mcq.option3}} <br>
                                <input type="radio" id=Option value="4" class="rb" name="user_answer"> {{mcq.option4}}<br>
                                <br>
                            {% endif %}
                        {% endfor %}    
                    {% elif question.question_type == "FillInTheBlanks" %}<br>
                        <input type="text" id=user_answer name="user_answer" class="rb"> <br>                <hr>  
                    {% endif %}
    <div>
        {% if is_paginated %}
            {% if page_obj.has_next %}
            <input class="btn btn-outline-primary" href="?page={{ page_obj.next_page_number }}" 
            form="myform" type="submit" value="Next">
        {% else %}
            <input class="btn btn-outline-info" href="{% url 'quiz:result_page' %}" form="myform" type="submit" value="Submit">
            {% endif %}
        {% endif %}
    </div>
</form>
{% endfor %}


<script src="{% static 'script.js' %}"></script>
<script>
    timer("{% url 'quiz:result_page' %}")
</script>

{% endblock content %}

templates/result.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="card text-left"> 
    <div class="card-body"> 
        <h2>Hi {{ user.email }}</h2>
        <h5 class="text-primary"> You have answered {{ user_score }} questions correctly,
        out of {{total_questions}} questions </h5>
            <input type="submit" value="Click to check answers" id="button1" class="btn btn-success" onclick="getanswers();" /> <br>
      <b id="UserAnswers"></b>
    </div>
</div>


<script>
    function getanswers() {
        document.getElementById("UserAnswers").innerHTML = `
        <p>{% for answer_given in answer_given %}
                {% if answer_given.user_answer_mcq %} <br>
                    {% for mcq in mcq %}
                        {% if answer_given.question.id == mcq.question.id %}
                            <u> {{answer_given.question }} </u>
                                <br>Option 1: {{ mcq.option1 }}
                                <br>Option 2: {{ mcq.option2 }}
                                <br>Option 3: {{ mcq.option3 }}
                                <br>Option 4: {{ mcq.option4 }}
                        {% if answer_given.is_answer_correct == True %}
                            <br><p class="text-success">Congratulations!&#127881; You answered correctly.
                            <br><p class="text-success">You chose Option{{ answer_given.user_answer_mcq }}
                            <br>Answer is Option {{answer_given.user_answer_mcq}} </p>
                        {% else %}
                            <br><p class="text-danger">Incorrect Answer &#x2639
                            <br> <br>You choose Option {{answer_given.user_answer_mcq}}
                            <br>Correct Answer is Option{{mcq.correct_answer_mcq}} </p>
                        {% endif %}
                        {% endif %}
                    {% endfor %}
                    {% elif answer_given.user_answer_fill_in_the_blanks %}
                    <br>
                      {% for fill_in_the_blanks in fill_in_the_blanks %}
                        {% if answer_given.question.id == fill_in_the_blanks.question.id %}
                          {% if answer_given.is_answer_correct == True %}
                            <br><u>{{answer_given.question}}</u>
                            <br><p class="text-success">Congratulations!&#127881; You answered correctly.</p>
                            <p class="text-success">You answered : {{ answer_given.user_answer_fill_in_the_blanks }}
                            <br>Answer is : {{fill_in_the_blanks.correct_answer_fill_in_the_blanks }} </p>
                          {% else %}
                            <br><u>{{answer_given.question }}</u>
                            <br><p class="text-danger">Incorrect Answer &#x2639 
                            <br><br>You answered : {{answer_given.user_answer_fill_in_the_blanks }}
                            <br>Correct Answer is : {{fill_in_the_blanks.correct_answer_fill_in_the_blanks}} </p>
                          {% endif %}
                        {% endif %}
                      {% endfor %}
                    {% endif %}
                  {% endfor%}
        </p>
        `;
  }
</script>
{% endblock content %}

templates/start_page.html
{% extends "base.html" %}
{% load crispy_forms_tags%}
{% block content %}

<div class="card text-left"> 
    <div class="card-body"> 
        
        {% if user.is_authenticated %}
            <h4>Hi {{user.email}}</h4> 
            <h5>If you have not attempted all of the questions you can resume quiz by clicking the button below. <p></p> <a class="btn btn-success" href="{% url 'quiz:question_page' %}">Resume Quiz</a></h5>
            <h5>If you have already completed the quiz, you can view your results by clicking the results button below. <p></p> <a class="btn btn-warning" href="{% url 'quiz:result_page' %}">Show Results</a></h5>
        {% else %}
            <h2>Welcome to Quiz Me</h2>
            If you don't have an account,<br><a class="btn btn-primary" href="{% url 'accounts:signup' %}">SignUp </a> <br>
            Already Have An Account? <br> <a class="btn btn-success" href="{% url 'accounts:login'%}">LogIn</a> <p></p>
            <h5>Instructions for quiz:</h5>
            <ul>
            <li>Once you login, the quiz will start directly.</li>
            <li>Once you attempt a question, you can't go back to the last question.</li>
            <li>You can only attempt all the questions once, you cannot retake the quiz.</li>
            <li>Once the timer ends, the form would be auto-submitted with the questions you have attempted and results would be shown.</li>
            <li>If you logout in the middle of the quiz, you can resume the quiz from the last question you were in.</li>
            </ul>
        {% endif %}
    </div>
</div>
{% endblock content %}